server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.cloud.gateway.server.webmvc.routes[0].id=auth-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://AUTHSERVICE
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/authservice/**
spring.cloud.gateway.server.webmvc.routes[0].filters[0]=RewritePath=/authservice/?(?<segment>.*), /${segment}

spring.cloud.gateway.server.webmvc.routes[1].id=train-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://TRAINSERVICE
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/trainservice/**
spring.cloud.gateway.server.webmvc.routes[1].filters[0]=RewritePath=/trainservice/?(?<segment>.*), /${segment}
